version: '3'

volumes:
  postgres:
  redis:

services:
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    volumes:
      - redis:/data

  web:
    depends_on:
      - postgres
      - redis
    environment:
      DISABLE_SPRING: 'true'
    image: ruby:3.0
    volumes:
      - .:/app
      - .bundle:/usr/local/bundle
    working_dir: /app
    ports:
      - 3000:3000
    command: bundle exec rails s -b 0.0.0.0
